### ISSUE TITLE
BrainFuck: Pip Installation fails

### ISSUE THREAD

**Issue by DevynCJohnson** [gfyoung/brainfuck#1]
Ubuntu 15.10

Python3.4

```
root@Nacho-Linux:/home/collier# pip3 install brainfuck
Collecting brainfuck
  Downloading brainfuck-1.0.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-eduoxjo6/brainfuck/setup.py", line 1, in <module>
        from brainfuck import version
      File "/tmp/pip-build-eduoxjo6/brainfuck/brainfuck/__init__.py", line 52, in <module>
        import Base
    ImportError: No module named 'Base'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-eduoxjo6/brainfuck
```

**Comment by gfyoung** [comment]
Yikes!  Good catch.  Looks like the import syntax needs to be fixed (not just in this file but also all the others) to satisfy that of Python 3.  Do you think you can put up a PR to fix all of these import errors?  To test if your changes work, run ```python setup.py build_ext -i``` from the top ```brainfuck``` directory.

**Comment by gfyoung** [comment]
EDIT: The changes are actually a lot simpler than I thought.  I'm going to push them to ```master``` by the end of today and then release a new version so that Python 3 users can download this.  I'll make a note here once I can successfully make the changes.

**Comment by gfyoung** [comment]
I just uploaded a new release of ```brainfuck``` with PyPi that <i>should</i> download properly now with Python 3.  Thanks again for pointing this out, and, if you could, make sure to share this package with others!
