### ISSUE TITLE
Suggested minor? tweaks.

### ISSUE THREAD

**Issue by rdebath** [gfyoung/brainfuck#2]
Speed ...

As expected this is a very slow interpreter, the following piece of code prints out the alphabet (more and more slowly), however, you don't see the initial characters before it (eventually) finishes. Normally you should.

```brainfuck
>++++++++[>+++>>>++++++++<<<<-]>++<<+[>>>[>>]<[[->>+<<]>>>+.[->>+<<]<-[<<]]>+<<[-<<]<]>+>>[-<<]<+++++++++.
```

Secondly, this code should print the word 'brainfuck' (no NL) but because of the "non-standard" nature of your standard interpreter it doesn't, is this intentional?

```brainfuck
+[[->]-[-<]>-]>.>>>>.<<<<-.>>-.>.<<.>>>>-.[<]>++.>>++.
```

Thirdly, how do I run 'large' code.
eg: You're too slow for ["this"](https://github.com/rdebath/Brainfuck/blob/master/testing/Euler5-multisize.b) even though it should work perfectly if I were patient enough but you should be fast enough for ["this"](https://github.com/rdebath/Brainfuck/blob/master/testing/LostKng.b) and it even looks like it's working with your unusual cells.

**Comment by gfyoung** [comment]
Could you split up this issue into separate issues?  It seems like you are addressing several different problems at once, and splitting them up (with more descriptive titles) would be great!

**Comment by rdebath** [comment]
As you wish ...

**Comment by gfyoung** [comment]
@rdebath : Thanks so much!  Much appreciated.
