### ISSUE TITLE
Character buffering

### ISSUE THREAD

**Issue by rdebath** [gfyoung/brainfuck#3]
As expected this is a very slow interpreter, the following piece of code prints out the alphabet (more and more slowly), however, you don't see the initial characters before it (eventually) finishes. Normally you should.

```brainfuck
>++++++++[>+++>>>++++++++<<<<-]>++<<+[>>>[>>]<[[->>+<<]>>>+.[->>+<<]<-[<<]]>+<<[-<<]<]>+>>[-<<]<+++++++++.
```

**Comment by gfyoung** [comment]
If I understand your issue correctly, you are saying that the characters are not being printed out until <b>after</b>the code finishes running.  What is your setup?  I just tried running your code on Windows 64, Python 2.7.11, and I do see the characters before the code finishes running.

**Comment by rdebath** [comment]
Humm ...
```
$ python3 -V
Python 3.4.2
$ python -V
Python 2.7.9
$ 
```
For me 'print' is buffered this is unbuffered ...
```
os.write(1, chr(m[p]).encode('ascii'))
```
This is buffered ...
```
sys.stdout.write(chr(m[p]))
```
I need to add this to flush the buffer...
```
sys.stdout.flush()
```
Are you on Windows or Linux/Unix ?

**Comment by gfyoung** [comment]
Ah, so it is an OS issue.  Just replicated on Linux.

**Comment by gfyoung** [comment]
Would you like to put up a patch for this?

**Comment by gfyoung** [comment]
You should be able to run the alphabet printing code with the console displaying the characters as it goes along.  Should I close this, or do you want to keep it open for performance reasons?

**Comment by rdebath** [comment]
This is working nicely too.
