### ISSUE TITLE
Cell size

### ISSUE THREAD

**Issue by rdebath** [gfyoung/brainfuck#4]
This code should print the word 'brainfuck' (no NL) but because of the "non-standard" nature of your standard interpreter it doesn't, is this intentional?

```brainfuck
+[[->]-[-<]>-]>.>>>>.<<<<-.>>-.>.<<.>>>>-.[<]>++.>>++.
```

**Comment by gfyoung** [comment]
Nope, totally a bug there.  Probably an issue related to character printing, so that definitely seems like the first place to check.  Also, could you enumerate a little further on what you mean by "non-standard"?

**Comment by rdebath** [comment]
Your cell size is 7 bits not 8 bits.

**Comment by gfyoung** [comment]
Ah.  Perhaps that might explain why you're seeing this issue.  I'm using <b>signed</b>8-bit integers.  Does your code assume <b>unsigned</b>8-bit integers?

**Comment by gfyoung** [comment]
Ah...yes, indeed.  I had intended to do <b>signed</b> 8-bit integers, but I completely forgot the negative half!  Yikes!  Now that I think about it, <b>unsigned</b> 8-bit is probably better.

**Comment by rdebath** [comment]
There's no difference between signed and unsigned cells in BF. It is impossible for the BF program to detect if the host language would choose to interpret the cell as signed or unsigned as long as the cell wraps. 

This is because the only BF condition is "equals zero" there's no instruction for "greater than". 

... Ah okay you see now :smile:

**Comment by gfyoung** [comment]
Indeed, my fingers were faster to type than my brain was to put something logical in the comment box.  :smile: Should be a simple fix.

**Comment by gfyoung** [comment]
Cells are now 8-bit, and your code works as described.  Thanks!
