### ISSUE TITLE
Large programs

### ISSUE THREAD

**Issue by rdebath** [gfyoung/brainfuck#5]
How do I run 'large' code.

For example: You're too slow for ["this"](https://github.com/rdebath/Brainfuck/blob/master/testing/Euler5-multisize.b) even though it should work perfectly if I were patient enough but you should be fast enough for ["this"](https://github.com/rdebath/Brainfuck/blob/master/testing/LostKng.b) and it even looks like it's working with your unusual cells.

**Comment by gfyoung** [comment]
I'm not sure I quite understand your question.  The wording in your example seems a little unclear.

Also, just to double check, you are aware of the `-f` flag to run `brainfuck` code, correct?

**Comment by rdebath** [comment]
Well, that always prints "Invalid brainfuck file", I guess it's another troll thing.

**Comment by gfyoung** [comment]
You know why: it's because my code doesn't accept the `.b` file extension.  That totally needs to be added though.  I only currently accept the `.bf` file extension.

**Comment by rdebath** [comment]
Ah, "bf" tends to mean [Befunge](http://esolangs.org/wiki/Befunge]), a much more evil language than brainfuck, however, for the truly evil languages you want to look around [Malbolge](http://esolangs.org/wiki/Malbolge).

Anyway, why do you insist on a particular extension at all ?

**Comment by gfyoung** [comment]
Ah, you raise a good point.  If the interpreting language is flexible on file extensions, why should I go against that? :smile:

**Comment by gfyoung** [comment]
Just updated `master` to remove the code restriction.  Your files <i>should</i> be able to run now, albeit not very quickly :smile:

**Comment by gfyoung** [comment]
Is this issue related to just not being able to run your `brainfuck` files, or do you want to keep this open for performance reasons?

**Comment by rdebath** [comment]
Yup, it looks like they're running nicely now.

As for performance, if you were to switch to an "eval" style you might manage a five or six times improvement in speed, but Python is a pretty slow interpreter and I don't see you getting anywhere near the one or two thousand times faster that's possible with other implementations without some drastic measures. 

So if you want performance "issues" I'd say open new ones when you choose a possible strategy. 
(eg: a one, or other, of the Python compilers or some sort of JIT).

**Comment by gfyoung** [comment]
Yeah, I knew going in that writing a Python interpreter was not going to be fast.  If I wanted fast, a <i>much lower</i> would have been required. :smile:   I was only asking in the context of the issue you had opened.

**Comment by gfyoung** [comment]
Also, in a different vein, why would I want to optimize a library whose deliberate intention is further screw with somebody's mind? :wink:

**Comment by rdebath** [comment]
Is "going slow" a brainfuck? I thought it was just boredom...
Now, OTOH, impossibly fast might be a brainfuck, maybe. 

I suppose a good brainfuck could be a BF variant that's sufficiently random that you can a "Hello World" but anything larger is just too difficult.

Your "chars" isn't good enough though because a [trivial translation](https://esolangs.org/wiki/TrivialBrainfuckSubstitution) makes it completely reliable ... for example ...

```
>abc1+ghi3+ghi3+ghi3+ghi3+ghi3+ghi3+ghi3+ghi3[stu7-jkl4<def2+ghi3+ghi3+ghi
3+ghi3+ghi3+ghi3+ghi3+ghi3+ghi3>abc1]vwx8<def2.mno5>abc1[stu7]vwx8[stu7<de
f2-jkl4]vwx8>abc1+ghi3>abc1-jkl4[stu7+ghi3]vwx8+ghi3+ghi3>abc1+ghi3+ghi3>a
bc1+ghi3+ghi3+ghi3[stu7>abc1[stu7-jkl4>abc1+ghi3+ghi3+ghi3<def2<def2+ghi3+
ghi3+ghi3>abc1]vwx8<def2<def2]vwx8>abc1-jkl4-jkl4-jkl4-jkl4-jkl4.mno5>abc1
-jkl4>abc1+ghi3+ghi3+ghi3.mno5.mno5+ghi3+ghi3+ghi3.mno5>abc1-jkl4.mno5<def
2<def2+ghi3[stu7>abc1[stu7+ghi3>abc1+ghi3]vwx8>abc1>abc1]vwx8<def2-jkl4-jk
l4-jkl4-jkl4-jkl4-jkl4-jkl4-jkl4-jkl4-jkl4-jkl4-jkl4-jkl4-jkl4.mno5>abc1>a
bc1.mno5+ghi3+ghi3+ghi3.mno5-jkl4-jkl4-jkl4-jkl4-jkl4-jkl4.mno5-jkl4-jkl4-
jkl4-jkl4-jkl4-jkl4-jkl4-jkl4.mno5>abc1+ghi3.mno5>abc1+ghi3.mno5
```

**Comment by gfyoung** [comment]
If you're willing to write code that's 5x as long as it should be...more power to you. :smile: 
Also, the other interpreters are not <i>all</i> just about trivial substitution.

**Comment by rdebath** [comment]
Um, it's Brainfuck, it's already tens or hundreds of times longer than it "should be".

[Here's](https://gist.github.com/rdebath/75e444c5738a6ccbc17c) the output from the sed script of a program that "should be" a few kilobytes. 
```
#!/bin/sed -f
:slurp
$ !{
  N
  b slurp
}
s/[^]<>+,-.[]//g
y/]<>+,-.[/ELRUIDOB/

s/R/>abc1/g
s/L/<def2/g
s/U/+ghi3/g
s/D/-jkl4/g
s/O/.mno5/g
s/I/,pqr6/g
s/B/[stu7/g
s/E/]vwx8/g

s/[^\n]\{74\}/&\n/g
s/  *\(\n\|$\)/\1/g
```

**Comment by rdebath** [comment]
It looks like I might be wrong ...
This Python BF is a bit quick https://github.com/alexprengere/PythonBrainFuck
All the heavy lifting is done by [pypy](http://pypy.org/), [RPython](http://readthedocs.org/docs/pypy/en/latest/coding-guide.html#restricted-python) and it's [JIT](https://morepypy.blogspot.co.uk/2011/04/tutorial-part-2-adding-jit.html)

**Comment by gfyoung** [comment]
Good to know!  Thanks @rdebath !
